import type { ArchitectureSchema } from '@kalio/types';

export const STRATEGIC_DECISION_COUNCIL: ArchitectureSchema = {
  id: 'strategic-decision-council',
  name: 'Strategic Decision Council',
  description: 'Parallel role deliberation with a router and final artifact synthesis.',
  version: '0.1.0',
  roleSlots: [
    {
      id: 'pragmatist',
      label: 'Pragmatist',
      description: 'Optimizes for shippable, low-risk execution.',
      slotType: 'participant',
      defaultPersonaId: 'dev',
      allowedPersonaTags: ['strategy', 'delivery'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'innovator',
      label: 'Innovator',
      description: 'Surfaces non-obvious options and leverage.',
      slotType: 'participant',
      defaultPersonaId: 'jony',
      allowedPersonaTags: ['strategy', 'innovation', 'ux'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'analyst',
      label: 'Analyst',
      description: 'Checks facts, constraints, and trade-offs.',
      slotType: 'participant',
      defaultPersonaId: 'web-research',
      allowedPersonaTags: ['analysis', 'cost', 'evidence'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'user_advocate',
      label: 'User Advocate',
      description: 'Defends user value and usability.',
      slotType: 'participant',
      defaultPersonaId: 'designer',
      allowedPersonaTags: ['ux', 'product'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'shadow',
      label: 'Shadow',
      description: 'Challenges assumptions and failure modes.',
      slotType: 'critic',
      defaultPersonaId: 'orchestrator',
      allowedPersonaTags: ['risk', 'security', 'critique'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'router',
      label: 'Router',
      description: 'Selects the strongest path through deliberation.',
      slotType: 'router',
      defaultPersonaId: 'orchestrator',
      allowedPersonaTags: ['synthesis', 'decision', 'architecture'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'finalizer',
      label: 'Finalizer',
      description: 'Produces the final decision artifact.',
      slotType: 'finalizer',
      defaultPersonaId: 'dev',
      allowedPersonaTags: ['writing', 'architecture'],
      required: true,
      canOverrideAtRunStart: true,
    },
  ],
  nodes: [
    {
      id: 'parallel-deliberation',
      label: 'Parallel Deliberation',
      kind: 'parallel',
      behavior: {
        mode: 'fan_out_all',
        fanOut: 'parallel',
        convergeToNodeId: 'router',
        description: 'Run every outgoing participant branch at the same time.',
      },
    },
    { id: 'pragmatist', label: 'Pragmatist', kind: 'role', roleSlotId: 'pragmatist' },
    { id: 'innovator', label: 'Innovator', kind: 'role', roleSlotId: 'innovator' },
    { id: 'analyst', label: 'Analyst', kind: 'role', roleSlotId: 'analyst' },
    { id: 'user-advocate', label: 'User Advocate', kind: 'role', roleSlotId: 'user_advocate' },
    { id: 'shadow', label: 'Shadow', kind: 'role', roleSlotId: 'shadow' },
    {
      id: 'router',
      label: 'Router',
      kind: 'router',
      roleSlotId: 'router',
      behavior: {
        mode: 'rank_then_merge',
        fanOut: 'sequential',
        convergeToNodeId: 'final-artifact',
        scoringPolicy: 'risk',
        description: 'Rank incoming role outputs, merge the decision, and continue to the artifact node.',
      },
    },
    {
      id: 'final-artifact',
      label: 'Final Artifact',
      kind: 'artifact',
      roleSlotId: 'finalizer',
      behavior: {
        mode: 'finalize',
        description: 'Produce the final artifact from merged router output.',
      },
    },
  ],
  edges: [
    { id: 'parallel-pragmatist', fromNodeId: 'parallel-deliberation', toNodeId: 'pragmatist' },
    { id: 'parallel-innovator', fromNodeId: 'parallel-deliberation', toNodeId: 'innovator' },
    { id: 'parallel-analyst', fromNodeId: 'parallel-deliberation', toNodeId: 'analyst' },
    { id: 'parallel-user-advocate', fromNodeId: 'parallel-deliberation', toNodeId: 'user-advocate' },
    { id: 'parallel-shadow', fromNodeId: 'parallel-deliberation', toNodeId: 'shadow' },
    { id: 'pragmatist-router', fromNodeId: 'pragmatist', toNodeId: 'router' },
    { id: 'innovator-router', fromNodeId: 'innovator', toNodeId: 'router' },
    { id: 'analyst-router', fromNodeId: 'analyst', toNodeId: 'router' },
    { id: 'user-advocate-router', fromNodeId: 'user-advocate', toNodeId: 'router' },
    { id: 'shadow-router', fromNodeId: 'shadow', toNodeId: 'router' },
    { id: 'router-final-artifact', fromNodeId: 'router', toNodeId: 'final-artifact' },
  ],
  routerPolicy: {
    mode: 'rank_then_merge',
    mustAddressCriticFindings: true,
    canReturnNeedsMoreResearch: true,
  },
  contextPolicy: {
    includeUserTask: true,
    includeProjectMemory: true,
    includeBrowserSession: false,
    includePriorDecisions: true,
  },
  memoryPolicy: {
    persistFinalArtifact: false,
    persistRouterDecision: false,
  },
  outputArtifactSchema: 'ArchitectureDecisionArtifact',
};

export const FIVE_MINDS_COUNCIL: ArchitectureSchema = {
  id: 'five-minds-council',
  name: 'Five Minds Council',
  description: 'Adversarial five-perspective debate adapted from Agent Architecture Lab for Kalio runtime.',
  version: '0.1.0',
  roleSlots: [
    {
      id: 'pragmatist',
      label: 'Pragmatist',
      description: 'Tests feasibility, delivery cost, implementation risk, and smallest useful next step.',
      slotType: 'participant',
      defaultPersonaId: 'dev',
      allowedPersonaTags: ['delivery', 'implementation', 'strategy'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'innovator',
      label: 'Innovator',
      description: 'Looks for leverage, stronger UX/product moves, and non-obvious solution paths.',
      slotType: 'participant',
      defaultPersonaId: 'jony',
      allowedPersonaTags: ['innovation', 'ux', 'product'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'analyst',
      label: 'Analyst',
      description: 'Demands evidence, constraints, metrics, and explicit trade-offs.',
      slotType: 'participant',
      defaultPersonaId: 'web-research',
      allowedPersonaTags: ['analysis', 'research', 'evidence'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'user_advocate',
      label: 'User Advocate',
      description: 'Defends end-user clarity, accessibility, workflow ergonomics, and demo usefulness.',
      slotType: 'participant',
      defaultPersonaId: 'designer',
      allowedPersonaTags: ['ux', 'product', 'design'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'devil_advocate',
      label: "Devil's Advocate",
      description: 'Actively challenges assumptions, hidden failure modes, premature scope, and weak evidence.',
      slotType: 'critic',
      defaultPersonaId: 'orchestrator',
      allowedPersonaTags: ['risk', 'critique', 'security'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'synthesizer',
      label: 'Synthesizer',
      description: 'Merges the debate into a ranked recommendation and routes unresolved risks.',
      slotType: 'router',
      defaultPersonaId: 'orchestrator',
      allowedPersonaTags: ['synthesis', 'decision', 'architecture'],
      required: true,
      canOverrideAtRunStart: true,
    },
    {
      id: 'finalizer',
      label: 'Finalizer',
      description: 'Turns the synthesis into an actionable decision artifact with next steps.',
      slotType: 'finalizer',
      defaultPersonaId: 'dev',
      allowedPersonaTags: ['writing', 'architecture', 'delivery'],
      required: true,
      canOverrideAtRunStart: true,
    },
  ],
  nodes: [
    {
      id: 'five-minds-debate',
      label: 'Five Minds Debate',
      kind: 'parallel',
      behavior: {
        mode: 'fan_out_all',
        fanOut: 'parallel',
        convergeToNodeId: 'synthesizer',
        description: 'Run the five debate perspectives in parallel before synthesis.',
      },
    },
    { id: 'pragmatist', label: 'Pragmatist', kind: 'role', roleSlotId: 'pragmatist' },
    { id: 'innovator', label: 'Innovator', kind: 'role', roleSlotId: 'innovator' },
    { id: 'analyst', label: 'Analyst', kind: 'role', roleSlotId: 'analyst' },
    { id: 'user-advocate', label: 'User Advocate', kind: 'role', roleSlotId: 'user_advocate' },
    { id: 'devil-advocate', label: "Devil's Advocate", kind: 'role', roleSlotId: 'devil_advocate' },
    {
      id: 'synthesizer',
      label: 'Synthesizer',
      kind: 'router',
      roleSlotId: 'synthesizer',
      behavior: {
        mode: 'rank_then_merge',
        fanOut: 'sequential',
        convergeToNodeId: 'final-artifact',
        scoringPolicy: 'risk',
        description: 'Resolve conflicting perspectives, keep unresolved risk visible, and choose the strongest path.',
      },
    },
    {
      id: 'final-artifact',
      label: 'Decision Artifact',
      kind: 'artifact',
      roleSlotId: 'finalizer',
      behavior: {
        mode: 'finalize',
        description: 'Produce a final decision, recommended next action, and risk list.',
      },
    },
  ],
  edges: [
    { id: 'debate-pragmatist', fromNodeId: 'five-minds-debate', toNodeId: 'pragmatist' },
    { id: 'debate-innovator', fromNodeId: 'five-minds-debate', toNodeId: 'innovator' },
    { id: 'debate-analyst', fromNodeId: 'five-minds-debate', toNodeId: 'analyst' },
    { id: 'debate-user-advocate', fromNodeId: 'five-minds-debate', toNodeId: 'user-advocate' },
    { id: 'debate-devil-advocate', fromNodeId: 'five-minds-debate', toNodeId: 'devil-advocate' },
    { id: 'pragmatist-synthesizer', fromNodeId: 'pragmatist', toNodeId: 'synthesizer' },
    { id: 'innovator-synthesizer', fromNodeId: 'innovator', toNodeId: 'synthesizer' },
    { id: 'analyst-synthesizer', fromNodeId: 'analyst', toNodeId: 'synthesizer' },
    { id: 'user-advocate-synthesizer', fromNodeId: 'user-advocate', toNodeId: 'synthesizer' },
    { id: 'devil-advocate-synthesizer', fromNodeId: 'devil-advocate', toNodeId: 'synthesizer' },
    { id: 'synthesizer-final-artifact', fromNodeId: 'synthesizer', toNodeId: 'final-artifact' },
  ],
  routerPolicy: {
    mode: 'rank_then_merge',
    mustAddressCriticFindings: true,
    canReturnNeedsMoreResearch: true,
  },
  contextPolicy: {
    includeUserTask: true,
    includeProjectMemory: true,
    includeBrowserSession: false,
    includePriorDecisions: true,
  },
  memoryPolicy: {
    persistFinalArtifact: false,
    persistRouterDecision: false,
  },
  outputArtifactSchema: 'ArchitectureDecisionArtifact',
};

export const FIVE_MINDS_STRATEGIC: ArchitectureSchema = {
  id: 'five-minds-strategic',
  name: 'Five Minds Strategic',
  description: 'Research fan-out followed by Five Minds debate, synthesis, decision presentation, and final artifact.',
  version: '0.1.0',
  roleSlots: [
    { id: 'tech_researcher', label: 'Tech Researcher', description: 'Finds technical constraints, source evidence, repo risks, and implementation options.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['research', 'technical', 'evidence'], required: true, canOverrideAtRunStart: true },
    { id: 'ux_researcher', label: 'UX Researcher', description: 'Finds user workflow risks, accessibility issues, and interface patterns.', slotType: 'participant', defaultPersonaId: 'designer', allowedPersonaTags: ['ux', 'research', 'product'], required: true, canOverrideAtRunStart: true },
    { id: 'docs_researcher', label: 'Docs Researcher', description: 'Checks project docs, contracts, and prior decisions before debate.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['docs', 'research', 'evidence'], required: true, canOverrideAtRunStart: true },
    { id: 'pragmatist', label: 'Pragmatist', description: 'Judges delivery feasibility and smallest shippable path.', slotType: 'participant', defaultPersonaId: 'dev', allowedPersonaTags: ['delivery', 'implementation'], required: true, canOverrideAtRunStart: true },
    { id: 'innovator', label: 'Innovator', description: 'Searches for leverage, product lift, and non-obvious alternatives.', slotType: 'participant', defaultPersonaId: 'jony', allowedPersonaTags: ['innovation', 'ux'], required: true, canOverrideAtRunStart: true },
    { id: 'analyst', label: 'Analyst Expert', description: 'Forces evidence, metrics, trade-offs, and explicit assumptions.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['analysis', 'evidence'], required: true, canOverrideAtRunStart: true },
    { id: 'user_advocate', label: 'User Advocate', description: 'Protects power-user workflow clarity and demo usefulness.', slotType: 'participant', defaultPersonaId: 'designer', allowedPersonaTags: ['ux', 'product'], required: true, canOverrideAtRunStart: true },
    { id: 'devil_advocate', label: "Devil's Advocate", description: 'Challenges weak assumptions, hidden risks, and incomplete verification.', slotType: 'critic', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['risk', 'critique'], required: true, canOverrideAtRunStart: true },
    { id: 'synthesizer', label: 'Synthesizer', description: 'Ranks, merges, and exposes accepted and rejected inputs.', slotType: 'router', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['synthesis', 'decision'], required: true, canOverrideAtRunStart: true },
    { id: 'decision_presenter', label: 'Decision Presenter', description: 'Prepares the decision for HITL approval or follow-up routing.', slotType: 'judge', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['hitl', 'decision'], required: true, canOverrideAtRunStart: true },
    { id: 'finalizer', label: 'Finalizer', description: 'Writes the final architecture decision artifact.', slotType: 'finalizer', defaultPersonaId: 'dev', allowedPersonaTags: ['writing', 'architecture'], required: true, canOverrideAtRunStart: true },
  ],
  nodes: [
    { id: 'research-fanout', label: 'Research Fan-out', kind: 'parallel', behavior: { mode: 'fan_out_all', fanOut: 'parallel', convergeToNodeId: 'research-synthesis', description: 'Run independent research tracks before the debate.' } },
    { id: 'tech-researcher', label: 'Tech Researcher', kind: 'role', roleSlotId: 'tech_researcher', x: 120, y: 130 },
    { id: 'ux-researcher', label: 'UX Researcher', kind: 'role', roleSlotId: 'ux_researcher', x: 300, y: 130 },
    { id: 'docs-researcher', label: 'Docs Researcher', kind: 'role', roleSlotId: 'docs_researcher', x: 480, y: 130 },
    { id: 'research-synthesis', label: 'Research Synthesis', kind: 'router', roleSlotId: 'synthesizer', behavior: { mode: 'merge_inputs', fanOut: 'sequential', convergeToNodeId: 'five-minds-debate', scoringPolicy: 'confidence', description: 'Compress research into evidence for all five minds.' }, x: 320, y: 240 },
    { id: 'five-minds-debate', label: 'Five Minds Debate', kind: 'parallel', behavior: { mode: 'fan_out_all', fanOut: 'parallel', convergeToNodeId: 'strategic-synthesizer', description: 'Run five independent perspectives from the same evidence package.' }, x: 320, y: 340 },
    { id: 'pragmatist', label: 'Pragmatist', kind: 'role', roleSlotId: 'pragmatist', x: 80, y: 460 },
    { id: 'innovator', label: 'Innovator', kind: 'role', roleSlotId: 'innovator', x: 220, y: 460 },
    { id: 'analyst', label: 'Analyst Expert', kind: 'role', roleSlotId: 'analyst', x: 360, y: 460 },
    { id: 'user-advocate', label: 'User Advocate', kind: 'role', roleSlotId: 'user_advocate', x: 500, y: 460 },
    { id: 'devil-advocate', label: "Devil's Advocate", kind: 'role', roleSlotId: 'devil_advocate', x: 640, y: 460 },
    { id: 'strategic-synthesizer', label: 'Strategic Synthesizer', kind: 'router', roleSlotId: 'synthesizer', behavior: { mode: 'rank_then_merge', fanOut: 'sequential', convergeToNodeId: 'decision-presenter', scoringPolicy: 'risk', description: 'Merge debate results and keep unresolved conflicts visible.' }, x: 360, y: 580 },
    { id: 'decision-presenter', label: 'Decision Presenter', kind: 'role', roleSlotId: 'decision_presenter', x: 360, y: 700 },
    { id: 'final-artifact', label: 'Final Artifact', kind: 'artifact', roleSlotId: 'finalizer', behavior: { mode: 'finalize', description: 'Finalize the decision after the presentation gate.' }, x: 360, y: 820 },
  ],
  edges: [
    { id: 'research-tech', fromNodeId: 'research-fanout', toNodeId: 'tech-researcher' },
    { id: 'research-ux', fromNodeId: 'research-fanout', toNodeId: 'ux-researcher' },
    { id: 'research-docs', fromNodeId: 'research-fanout', toNodeId: 'docs-researcher' },
    { id: 'tech-research-synthesis', fromNodeId: 'tech-researcher', toNodeId: 'research-synthesis' },
    { id: 'ux-research-synthesis', fromNodeId: 'ux-researcher', toNodeId: 'research-synthesis' },
    { id: 'docs-research-synthesis', fromNodeId: 'docs-researcher', toNodeId: 'research-synthesis' },
    { id: 'research-synthesis-debate', fromNodeId: 'research-synthesis', toNodeId: 'five-minds-debate' },
    { id: 'debate-pragmatist', fromNodeId: 'five-minds-debate', toNodeId: 'pragmatist' },
    { id: 'debate-innovator', fromNodeId: 'five-minds-debate', toNodeId: 'innovator' },
    { id: 'debate-analyst', fromNodeId: 'five-minds-debate', toNodeId: 'analyst' },
    { id: 'debate-user-advocate', fromNodeId: 'five-minds-debate', toNodeId: 'user-advocate' },
    { id: 'debate-devil-advocate', fromNodeId: 'five-minds-debate', toNodeId: 'devil-advocate' },
    { id: 'pragmatist-synth', fromNodeId: 'pragmatist', toNodeId: 'strategic-synthesizer' },
    { id: 'innovator-synth', fromNodeId: 'innovator', toNodeId: 'strategic-synthesizer' },
    { id: 'analyst-synth', fromNodeId: 'analyst', toNodeId: 'strategic-synthesizer' },
    { id: 'user-synth', fromNodeId: 'user-advocate', toNodeId: 'strategic-synthesizer' },
    { id: 'devil-synth', fromNodeId: 'devil-advocate', toNodeId: 'strategic-synthesizer' },
    { id: 'synth-presenter', fromNodeId: 'strategic-synthesizer', toNodeId: 'decision-presenter' },
    { id: 'presenter-final', fromNodeId: 'decision-presenter', toNodeId: 'final-artifact' },
  ],
  routerPolicy: { mode: 'risk_weighted', mustAddressCriticFindings: true, canReturnNeedsMoreResearch: true },
  contextPolicy: {
    includeUserTask: true,
    includeProjectMemory: true,
    includeBrowserSession: true,
    includePriorDecisions: true,
    includeToolResults: true,
    perSlotOverrides: {
      synthesizer: { includeOtherAgentOutputs: true, includeToolResults: true, contextCompression: 'evidence_only' },
      finalizer: { includeOtherAgentOutputs: true, includeToolResults: true, contextCompression: 'summary' },
    },
  },
  memoryPolicy: { persistFinalArtifact: true, persistRouterDecision: true },
  outputArtifactSchema: 'ArchitectureDecisionArtifact',
};

export { GOAL_MASTER_DELIVERY_LOOP } from './architecture-seed-schemas.goal-master';

