import type { ArchitectureSchema } from '@kalio/types';

export const DEEP_FIVE_MINDS: ArchitectureSchema = {
  id: 'deep-five-minds',
  name: 'Deep Five Minds',
  description: 'Research swarm, critic review, Five Minds debate, delivery pod, QA gate, and bounded Goal Master loop.',
  version: '0.1.0',
  roleSlots: [
    { id: 'orchestrator', label: 'Orchestrator', description: 'Owns decomposition, routing, and final workflow continuity.', slotType: 'router', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['orchestration', 'planning'], required: true, canOverrideAtRunStart: true },
    { id: 'planner', label: 'Planner', description: 'Turns the task into phases, dependencies, and acceptance criteria.', slotType: 'participant', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['planning'], required: true, canOverrideAtRunStart: true },
    { id: 'tech_researcher', label: 'Tech Researcher', description: 'Finds technical constraints and implementation evidence.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['research', 'technical'], required: true, canOverrideAtRunStart: true },
    { id: 'ux_researcher', label: 'UX Researcher', description: 'Finds UX risks, accessibility constraints, and workflow evidence.', slotType: 'participant', defaultPersonaId: 'designer', allowedPersonaTags: ['research', 'ux'], required: true, canOverrideAtRunStart: true },
    { id: 'docs_researcher', label: 'Docs Researcher', description: 'Reads repo docs, contracts, and previous decisions.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['docs', 'evidence'], required: true, canOverrideAtRunStart: true },
    { id: 'research_critic', label: 'Research Critic', description: 'Challenges source quality, gaps, bias, and unsupported claims.', slotType: 'critic', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['critique', 'evidence'], required: true, canOverrideAtRunStart: true },
    { id: 'pragmatist', label: 'Pragmatist', description: 'Judges feasibility, cost, and smallest shippable path.', slotType: 'participant', defaultPersonaId: 'dev', allowedPersonaTags: ['delivery'], required: true, canOverrideAtRunStart: true },
    { id: 'innovator', label: 'Innovator', description: 'Proposes leverage, product lift, and non-obvious alternatives.', slotType: 'participant', defaultPersonaId: 'jony', allowedPersonaTags: ['innovation', 'ux'], required: true, canOverrideAtRunStart: true },
    { id: 'analyst', label: 'Analyst Expert', description: 'Forces metrics, assumptions, and trade-off clarity.', slotType: 'participant', defaultPersonaId: 'web-research', allowedPersonaTags: ['analysis'], required: true, canOverrideAtRunStart: true },
    { id: 'user_advocate', label: 'User Advocate', description: 'Protects end-user clarity and power-user workflow quality.', slotType: 'participant', defaultPersonaId: 'designer', allowedPersonaTags: ['ux', 'product'], required: true, canOverrideAtRunStart: true },
    { id: 'devil_advocate', label: "Devil's Advocate", description: 'Finds failure modes, hidden scope, and weak verification.', slotType: 'critic', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['risk', 'critique'], required: true, canOverrideAtRunStart: true },
    { id: 'synthesizer', label: 'Synthesizer', description: 'Merges research and debate into explicit accepted/rejected inputs.', slotType: 'router', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['synthesis'], required: true, canOverrideAtRunStart: true },
    { id: 'decision_presenter', label: 'Decision Presenter', description: 'Creates a human-readable gate before delivery execution.', slotType: 'judge', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['hitl', 'decision'], required: true, canOverrideAtRunStart: true },
    { id: 'backend', label: 'Backend Dev', description: 'Implements backend/runtime changes for the selected plan.', slotType: 'participant', defaultPersonaId: 'dev', allowedPersonaTags: ['backend', 'implementation'], required: true, canOverrideAtRunStart: true },
    { id: 'frontend', label: 'Frontend Dev', description: 'Implements UI and workflow changes for the selected plan.', slotType: 'participant', defaultPersonaId: 'dev', allowedPersonaTags: ['frontend', 'implementation'], required: true, canOverrideAtRunStart: true },
    { id: 'ux_designer', label: 'UX Designer', description: 'Polishes visual hierarchy, density, and interaction ergonomics.', slotType: 'participant', defaultPersonaId: 'designer', allowedPersonaTags: ['ux', 'design'], required: true, canOverrideAtRunStart: true },
    { id: 'qa_quality', label: 'QA Quality', description: 'Runs targeted regression and workflow verification.', slotType: 'critic', defaultPersonaId: 'dev', allowedPersonaTags: ['qa', 'testing'], required: true, canOverrideAtRunStart: true },
    { id: 'goal_master', label: 'Goal Master', description: 'Accepts only when evidence proves the goal; otherwise routes back to delivery.', slotType: 'judge', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['goal', 'review'], required: true, canOverrideAtRunStart: true },
    { id: 'finalizer', label: 'Finalizer', description: 'Writes verified result, evidence, risks, and next best action.', slotType: 'finalizer', defaultPersonaId: 'orchestrator', allowedPersonaTags: ['writing'], required: true, canOverrideAtRunStart: true },
  ],
  nodes: [
    { id: 'orchestrator', label: 'Orchestrator', kind: 'router', roleSlotId: 'orchestrator', behavior: { mode: 'choose_one', fanOut: 'sequential', convergeToNodeId: 'planning', scoringPolicy: 'risk', description: 'Start the architecture unless the orchestrator returns a different routeToNodeId.' }, x: 420, y: 40 },
    { id: 'planning', label: 'Planning', kind: 'role', roleSlotId: 'planner', x: 420, y: 160 },
    { id: 'research-swarm', label: 'Research Swarm', kind: 'parallel', behavior: { mode: 'fan_out_all', fanOut: 'parallel', convergeToNodeId: 'research-critic', description: 'Fan out independent evidence gathering.' }, x: 420, y: 280 },
    { id: 'tech-researcher', label: 'Tech Researcher', kind: 'role', roleSlotId: 'tech_researcher', x: 120, y: 400 },
    { id: 'ux-researcher', label: 'UX Researcher', kind: 'role', roleSlotId: 'ux_researcher', x: 320, y: 400 },
    { id: 'docs-researcher', label: 'Docs Researcher', kind: 'role', roleSlotId: 'docs_researcher', x: 520, y: 400 },
    { id: 'research-critic', label: 'Research Critic', kind: 'role', roleSlotId: 'research_critic', x: 420, y: 520 },
    { id: 'research-synthesis', label: 'Research Synthesis', kind: 'router', roleSlotId: 'synthesizer', behavior: { mode: 'merge_inputs', fanOut: 'sequential', convergeToNodeId: 'five-minds-debate', scoringPolicy: 'confidence', description: 'Compress evidence into debate input.' }, x: 420, y: 640 },
    { id: 'five-minds-debate', label: 'Five Minds Debate', kind: 'parallel', behavior: { mode: 'fan_out_all', fanOut: 'parallel', convergeToNodeId: 'strategic-synthesis', description: 'Run the five perspectives independently.' }, x: 420, y: 760 },
    { id: 'pragmatist', label: 'Pragmatist', kind: 'role', roleSlotId: 'pragmatist', x: 60, y: 900 },
    { id: 'innovator', label: 'Innovator', kind: 'role', roleSlotId: 'innovator', x: 240, y: 900 },
    { id: 'analyst', label: 'Analyst Expert', kind: 'role', roleSlotId: 'analyst', x: 420, y: 900 },
    { id: 'user-advocate', label: 'User Advocate', kind: 'role', roleSlotId: 'user_advocate', x: 600, y: 900 },
    { id: 'devil-advocate', label: "Devil's Advocate", kind: 'role', roleSlotId: 'devil_advocate', x: 780, y: 900 },
    { id: 'strategic-synthesis', label: 'Strategic Synthesis', kind: 'router', roleSlotId: 'synthesizer', behavior: { mode: 'rank_then_merge', fanOut: 'sequential', convergeToNodeId: 'decision-presenter', scoringPolicy: 'risk', description: 'Select the delivery plan or request more research via routeToNodeId.' }, x: 420, y: 1040 },
    { id: 'decision-presenter', label: 'Decision Presenter', kind: 'role', roleSlotId: 'decision_presenter', x: 420, y: 1160 },
    { id: 'delivery-pod', label: 'Delivery Pod', kind: 'parallel', behavior: { mode: 'fan_out_all', fanOut: 'parallel', convergeToNodeId: 'qa-quality', description: 'Run implementation slices in parallel.' }, x: 420, y: 1280 },
    { id: 'backend', label: 'Backend Dev', kind: 'role', roleSlotId: 'backend', x: 220, y: 1400 },
    { id: 'frontend', label: 'Frontend Dev', kind: 'role', roleSlotId: 'frontend', x: 420, y: 1400 },
    { id: 'ux-designer', label: 'UX Designer', kind: 'role', roleSlotId: 'ux_designer', x: 620, y: 1400 },
    { id: 'qa-quality', label: 'QA Quality', kind: 'role', roleSlotId: 'qa_quality', x: 420, y: 1520 },
    { id: 'goal-master', label: 'Goal Master', kind: 'router', roleSlotId: 'goal_master', behavior: { mode: 'choose_one', fanOut: 'sequential', convergeToNodeId: 'final-artifact', scoringPolicy: 'confidence', description: 'Route to final-artifact only when acceptance evidence is complete; routeToNodeId=delivery-pod to continue.' }, x: 420, y: 1640 },
    { id: 'final-artifact', label: 'Final Artifact', kind: 'artifact', roleSlotId: 'finalizer', behavior: { mode: 'finalize', description: 'Finalize the verified delivery result.' }, x: 420, y: 1760 },
  ],
  edges: [
    { id: 'orchestrator-planning', fromNodeId: 'orchestrator', toNodeId: 'planning' },
    { id: 'planning-research', fromNodeId: 'planning', toNodeId: 'research-swarm' },
    { id: 'research-tech', fromNodeId: 'research-swarm', toNodeId: 'tech-researcher' },
    { id: 'research-ux', fromNodeId: 'research-swarm', toNodeId: 'ux-researcher' },
    { id: 'research-docs', fromNodeId: 'research-swarm', toNodeId: 'docs-researcher' },
    { id: 'tech-critic', fromNodeId: 'tech-researcher', toNodeId: 'research-critic' },
    { id: 'ux-critic', fromNodeId: 'ux-researcher', toNodeId: 'research-critic' },
    { id: 'docs-critic', fromNodeId: 'docs-researcher', toNodeId: 'research-critic' },
    { id: 'critic-synthesis', fromNodeId: 'research-critic', toNodeId: 'research-synthesis' },
    { id: 'synthesis-debate', fromNodeId: 'research-synthesis', toNodeId: 'five-minds-debate' },
    { id: 'debate-pragmatist', fromNodeId: 'five-minds-debate', toNodeId: 'pragmatist' },
    { id: 'debate-innovator', fromNodeId: 'five-minds-debate', toNodeId: 'innovator' },
    { id: 'debate-analyst', fromNodeId: 'five-minds-debate', toNodeId: 'analyst' },
    { id: 'debate-user', fromNodeId: 'five-minds-debate', toNodeId: 'user-advocate' },
    { id: 'debate-devil', fromNodeId: 'five-minds-debate', toNodeId: 'devil-advocate' },
    { id: 'pragmatist-strategy', fromNodeId: 'pragmatist', toNodeId: 'strategic-synthesis' },
    { id: 'innovator-strategy', fromNodeId: 'innovator', toNodeId: 'strategic-synthesis' },
    { id: 'analyst-strategy', fromNodeId: 'analyst', toNodeId: 'strategic-synthesis' },
    { id: 'user-strategy', fromNodeId: 'user-advocate', toNodeId: 'strategic-synthesis' },
    { id: 'devil-strategy', fromNodeId: 'devil-advocate', toNodeId: 'strategic-synthesis' },
    { id: 'strategy-presenter', fromNodeId: 'strategic-synthesis', toNodeId: 'decision-presenter' },
    { id: 'presenter-delivery', fromNodeId: 'decision-presenter', toNodeId: 'delivery-pod' },
    { id: 'delivery-backend', fromNodeId: 'delivery-pod', toNodeId: 'backend' },
    { id: 'delivery-frontend', fromNodeId: 'delivery-pod', toNodeId: 'frontend' },
    { id: 'delivery-ux', fromNodeId: 'delivery-pod', toNodeId: 'ux-designer' },
    { id: 'backend-qa', fromNodeId: 'backend', toNodeId: 'qa-quality' },
    { id: 'frontend-qa', fromNodeId: 'frontend', toNodeId: 'qa-quality' },
    { id: 'ux-qa', fromNodeId: 'ux-designer', toNodeId: 'qa-quality' },
    { id: 'qa-goal', fromNodeId: 'qa-quality', toNodeId: 'goal-master' },
    { id: 'goal-final', fromNodeId: 'goal-master', toNodeId: 'final-artifact', label: 'accepted' },
    { id: 'goal-redo', fromNodeId: 'goal-master', toNodeId: 'delivery-pod', label: 'continue' },
  ],
  routerPolicy: { mode: 'risk_weighted', mustAddressCriticFindings: true, canReturnNeedsMoreResearch: true },
  contextPolicy: {
    includeUserTask: true,
    includeProjectMemory: true,
    includeBrowserSession: true,
    includePriorDecisions: true,
    includeOtherAgentOutputs: true,
    includeToolResults: true,
    contextCompression: 'summary',
    perSlotOverrides: {
      synthesizer: { includeOtherAgentOutputs: true, includeToolResults: true, contextCompression: 'evidence_only' },
      goal_master: { includeOtherAgentOutputs: true, includeToolResults: true, contextCompression: 'evidence_only' },
      finalizer: { includeOtherAgentOutputs: true, includeToolResults: true, contextCompression: 'summary' },
    },
  },
  memoryPolicy: { persistFinalArtifact: true, persistRouterDecision: true },
  outputArtifactSchema: 'GoalCompletionArtifact',
};
