# Kalio Windows runtime installer
# Usage:
#   .\scripts\install.ps1 -ArchivePath .\kalio-runtime-1.0.0-windows-x64.zip
#   .\scripts\install.ps1 -ArchivePath .\kalio-runtime-1.0.0-windows-x64.zip -NoLaunch

param(
    [Parameter(Mandatory = $true)]
    [string]$ArchivePath,
    [string]$InstallRoot = '',
    [switch]$NoLaunch,
    [switch]$NoAutostart
)

$ErrorActionPreference = 'Stop'

function Write-Step {
    param([string]$Message)
    Write-Host "[kalio] $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[kalio] $Message" -ForegroundColor Green
}

function Assert-Version {
    param([string]$Version)
    if ($Version -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]*$') {
        throw "Invalid runtime version: $Version"
    }
}

function Assert-UnderRoot {
    param([string]$Path, [string]$Root)
    $resolvedPath = [IO.Path]::GetFullPath($Path)
    $resolvedRoot = [IO.Path]::GetFullPath($Root).TrimEnd('\') + '\'
    if (-not $resolvedPath.StartsWith($resolvedRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to operate outside install root: $resolvedPath"
    }
}

function Assert-RuntimeLockAvailable {
    param([string]$LockPath)

    if (-not (Test-Path -LiteralPath $LockPath -PathType Leaf)) {
        return
    }

    try {
        $lockOwner = Get-Content -LiteralPath $LockPath -Raw | ConvertFrom-Json
    } catch {
        throw "Kalio runtime lock cannot be verified safely: $LockPath"
    }
    if ($null -eq $lockOwner.pid -or [int]$lockOwner.pid -le 0) {
        throw "Kalio runtime lock does not contain a valid PID: $LockPath"
    }

    $ownerProcess = Get-Process -Id $lockOwner.pid -ErrorAction SilentlyContinue
    if ($ownerProcess) {
        throw "Kalio appears to be running; stop it before updating: $LockPath"
    }

    Write-Step "Removing stale runtime lock for dead PID $($lockOwner.pid)"
    Remove-Item -LiteralPath $LockPath -Force
}

function New-DataEnv {
    param([string]$DataRoot, [ValidateSet('node', 'bun')][string]$Runtime = 'node')

    $envPath = Join-Path $DataRoot '.env'
    if (Test-Path -LiteralPath $envPath) {
        Write-Step "Keeping existing data environment: $envPath"
        return
    }

    $bytes = New-Object byte[] 32
    $rng = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    $masterKey = [Convert]::ToBase64String($bytes)
    $dbPath = Join-Path $DataRoot 'kalio.db'
    $workspacePath = Join-Path $DataRoot 'workspaces'
    $memoryPath = Join-Path $DataRoot 'memory'
    $embeddingPath = Join-Path $DataRoot 'embeddings-cache'
    $content = @"
# Generated by Kalio runtime installer. Keep this file private.
NODE_ENV=production
PORT=4016
KALIO_HOST=127.0.0.1
KALIO_INSTALL_PROFILE=runtime
KALIO_SERVE_UI=true
KALIO_SQLITE_DRIVER=$Runtime
DATABASE_PATH=$dbPath
WORKSPACE_ROOT=$workspacePath
MEMORY_DB_PATH=$memoryPath
EMBEDDING_CACHE_DIR=$embeddingPath
CREDENTIALS_MASTER_KEY=$masterKey
CORS_ORIGIN=http://127.0.0.1:4016
LLM_PROVIDER=mock
LLM_API_KEY=mock
LLM_BASE_URL=mock
LLM_MODEL=mock
"@
    New-Item -ItemType Directory -Path $DataRoot -Force | Out-Null
    [IO.File]::WriteAllText($envPath, $content, (New-Object Text.UTF8Encoding($false)))
    Write-Ok "Created data environment: $envPath"
}

function Get-AutostartShortcutPath {
    $startupRoot = [Environment]::GetFolderPath('Startup')
    if (-not $startupRoot) {
        $startupRoot = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
    }
    return Join-Path $startupRoot 'Kalio Forever.lnk'
}

function Expand-RuntimeArchive {
    param([string]$ArchivePath, [string]$DestinationPath)

    $tarPath = Join-Path $env:SystemRoot 'System32\tar.exe'
    if (Test-Path -LiteralPath $tarPath -PathType Leaf) {
        & $tarPath -xf $ArchivePath -C $DestinationPath
        if ($LASTEXITCODE -ne 0) {
            throw "Windows tar failed to extract the runtime archive (exit $LASTEXITCODE)"
        }
        return
    }

    Expand-Archive -LiteralPath $ArchivePath -DestinationPath $DestinationPath -Force
}

function Remove-AutostartShortcut {
    $shortcutPath = Get-AutostartShortcutPath
    Remove-Item -LiteralPath $shortcutPath -Force -ErrorAction SilentlyContinue
}

function Remove-LegacyScheduledTasks {
    $schtasksPath = Join-Path $env:SystemRoot 'System32\schtasks.exe'
    if (-not (Test-Path -LiteralPath $schtasksPath -PathType Leaf)) {
        return
    }

    foreach ($taskName in @('Kalio Forever', 'Kalio-Forever')) {
        $process = Start-Process -FilePath $schtasksPath -ArgumentList @('/Delete', '/TN', ('"{0}"' -f $taskName), '/F') -WindowStyle Hidden -PassThru
        try {
            Wait-Process -Id $process.Id -Timeout 5 -ErrorAction Stop
        } catch {
            Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
            Write-Warning "Timed out while removing legacy Scheduled Task '$taskName'; it may require manual removal"
        }
    }
}

function Register-AutostartShortcut {
    param([string]$LauncherScript)

    $shortcutPath = Get-AutostartShortcutPath
    $startupRoot = Split-Path -Parent $shortcutPath
    New-Item -ItemType Directory -Path $startupRoot -Force | Out-Null
    $powershellPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $powershellPath
    $shortcut.Arguments = ('-NoLogo -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "{0}" serve' -f $LauncherScript)
    $shortcut.WorkingDirectory = Split-Path -Parent $LauncherScript
    $shortcut.WindowStyle = 7
    $shortcut.Description = 'Start Kalio after Windows sign-in'
    $shortcut.Save()
    Write-Ok "Registered per-user Startup shortcut: $shortcutPath"
}

try {
    $localAppData = [Environment]::GetFolderPath('LocalApplicationData')
    if (-not $localAppData) {
        $localAppData = Join-Path $env:USERPROFILE 'AppData\Local'
    }
    if (-not $InstallRoot) {
        $InstallRoot = Join-Path $localAppData 'Kalio'
    }
    $InstallRoot = [IO.Path]::GetFullPath($InstallRoot)
    $ArchivePath = [IO.Path]::GetFullPath($ArchivePath)
    if (-not (Test-Path -LiteralPath $ArchivePath -PathType Leaf)) {
        throw "Runtime archive not found: $ArchivePath"
    }

    $lockPath = Join-Path $InstallRoot '.runtime.lock'
    Assert-RuntimeLockAvailable -LockPath $lockPath
    $tempRoot = Join-Path ([IO.Path]::GetTempPath()) ('kalio-runtime-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tempRoot -Force | Out-Null
    try {
        Write-Step "Extracting runtime archive: $ArchivePath"
        Expand-RuntimeArchive -ArchivePath $ArchivePath -DestinationPath $tempRoot
        $metadataFile = Get-ChildItem -LiteralPath $tempRoot -Filter 'runtime.json' -File -Recurse | Select-Object -First 1
        if ($null -eq $metadataFile) {
            throw 'runtime.json is missing from the archive'
        }
        $metadata = Get-Content -LiteralPath $metadataFile.FullName -Raw | ConvertFrom-Json
        $runtime = if ($null -eq $metadata.runtime -or [string]::IsNullOrWhiteSpace([string]$metadata.runtime)) { 'node' } else { [string]$metadata.runtime }
        if ($runtime -notin @('node', 'bun')) {
            throw "Unsupported Kalio runtime: $runtime"
        }
        if ($metadata.platform -ne 'windows' -or $metadata.architecture -ne 'x64') {
            throw "This archive is not a Windows x64 Kalio runtime: $($metadata.platform)/$($metadata.architecture)"
        }
        Assert-Version -Version $metadata.version
        $sourceRoot = $metadataFile.Directory.FullName
        $versionsRoot = Join-Path $InstallRoot 'app\versions'
        $versionRoot = Join-Path $versionsRoot $metadata.version
        Assert-UnderRoot -Path $versionRoot -Root $versionsRoot
        New-Item -ItemType Directory -Path $versionsRoot -Force | Out-Null
        if (Test-Path -LiteralPath $versionRoot) {
            Write-Step "Replacing existing runtime version $($metadata.version)"
            Remove-Item -LiteralPath $versionRoot -Recurse -Force
        }
        Write-Step "Installing runtime version $($metadata.version)"
        Copy-Item -LiteralPath $sourceRoot -Destination $versionRoot -Recurse -Force

        $dataRoot = Join-Path $InstallRoot 'data'
        $requiredDirectories = @(
            (Join-Path $InstallRoot 'bin'),
            (Join-Path $InstallRoot 'logs'),
            (Join-Path $InstallRoot 'cache'),
            $dataRoot
        )
        foreach ($directory in $requiredDirectories) {
            New-Item -ItemType Directory -Path $directory -Force | Out-Null
        }
        New-DataEnv -DataRoot $dataRoot -Runtime $runtime

        $currentPath = Join-Path $InstallRoot 'current.json'
        $currentTemp = Join-Path $InstallRoot 'current.json.tmp'
        $current = @{
            version = $metadata.version
            runtime = $runtime
            platform = $metadata.platform
            architecture = $metadata.architecture
            apiProtocolVersion = $metadata.apiProtocolVersion
            databaseSchemaVersion = $metadata.databaseSchemaVersion
        } | ConvertTo-Json
        [IO.File]::WriteAllText($currentTemp, $current, (New-Object Text.UTF8Encoding($false)))
        Move-Item -LiteralPath $currentTemp -Destination $currentPath -Force

        $launcher = Join-Path $versionRoot 'bin\kalio.cmd'
        if (-not (Test-Path -LiteralPath $launcher)) {
            throw "Runtime launcher is missing: $launcher"
        }
        $packagedLauncherScript = Join-Path $versionRoot 'bin\kalio-launcher.ps1'
        if (-not (Test-Path -LiteralPath $packagedLauncherScript -PathType Leaf)) {
            throw "Stable launcher is missing from the runtime archive: $packagedLauncherScript"
        }
        $stableLauncherScript = Join-Path $InstallRoot 'bin\kalio-launcher.ps1'
        Copy-Item -LiteralPath $packagedLauncherScript -Destination $stableLauncherScript -Force
        $stableLauncher = Join-Path $InstallRoot 'bin\kalio.cmd'
        $stableLauncherContent = @'
@echo off
powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%~dp0kalio-launcher.ps1" %*
exit /b %ERRORLEVEL%
'@
        Set-Content -LiteralPath $stableLauncher -Value $stableLauncherContent -Encoding ASCII
        Remove-LegacyScheduledTasks
        if ($NoAutostart) {
            Remove-AutostartShortcut
            Write-Ok 'Autostart disabled by explicit request'
        } else {
            Register-AutostartShortcut -LauncherScript $stableLauncherScript
        }
        Write-Ok "Kalio runtime installed at $InstallRoot"
        Write-Host "  data -> $dataRoot" -ForegroundColor Green
        Write-Host "  run  -> $stableLauncher" -ForegroundColor Green
        if (-not $NoLaunch) {
            Write-Step 'Starting Kalio on localhost'
            Start-Process -FilePath $stableLauncher -ArgumentList 'start'
        }
    } finally {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
} catch {
    Write-Host "[kalio] FAIL $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
